### ISSUE TITLE
Add a feedback on error in the edit form, at the label level

### ISSUE THREAD

**Issue by Billybobbonnet** [WPRN/website#10]
https://github.com/WPRN/website/issues/8 made me desactivate the button check for validation of the first step of the edit form. It allows to go to the end of the form where the submit button is disabled (correct behavior since the form is invalid). However, it does not offer a feedback of where the form is invalid.

It is the same for every form step if we navigate through it using the step labels.

**Comment by Billybobbonnet** [comment]
Not low priority anymore: I noticed that project that have been created when description length was min 100 and that were under 500 char are not editable (since they do not have a long enough description.) It should provide a feedback (both at step level and at form level ) and it does not if the field is not focused once (in either, and it does if focus at step level).

**Comment by saadilahlou** [comment]
Add 400 blanks in them

**Comment by Billybobbonnet** [comment]
Done. We had, for many technical reasons, to disable the possibility to jump in the project steps in the project edit mode. I will restore this feature once we rewrite it to be 100% bound to the store.
