### ISSUE TITLE
Website subtitle: ImpactS and Capital letters

### ISSUE THREAD

**Issue by sluck-IEA** [WPRN/website#14]
Add an "s" to "impact" in the subtitle of the website on the splash page

If the "c" in covid is turned into a capital letter, maybe the first letter on the line should be too ("Assessing")

**Comment by Billybobbonnet** [comment]
First point noted.

About the second, one way to decide would be to answer this question: is "World Pandemic Research Network assessing the social and economic impacts of Covid19" a sentence? While it's not grammatically correct it still makes sense as a message. I'll leave the choice to @saadilahlou and you.

**Comment by Billybobbonnet** [comment]
Done
