### ISSUE TITLE
Tick all disciplines for a project

### ISSUE THREAD

**Issue by Sdbns** [WPRN/website#19]
Could we add a way to tick all disciplines at once? Or at least by category? 

I was thinking of the addition of a tick box in front of "Social Sciences and Humanities" and "Other sciences". Clicking on it would select all the disciplines in the category. 

This way we can tick all disciplines in two clicks.

**Comment by Billybobbonnet** [comment]
Afaik it can't be done with Vuetify (the component library). As it is not a strong use case, I'll close this. If both technical and UX sides are cleared, we'll reopen it.
