### ISSUE TITLE
Bug during a search

### ISSUE THREAD

**Issue by Sdbns** [WPRN/website#20]
When searching for the name of a project, the results are strangely displayed (see screenshot). 

![BUG SEARCH WPRN](https://user-images.githubusercontent.com/64425631/81196528-73a5e980-8fbf-11ea-99e4-9a2bc6c6bb1c.png)

**Comment by Sdbns** [comment]
The name of the project was : Impact of COVID-19 on STEM Students and Professionals

I have tried with another project name and there everything worked fine..

**Comment by Billybobbonnet** [comment]
Nice catch! :+1: I'll look into it.

**Comment by Billybobbonnet** [comment]
Fixed.
