### ISSUE TITLE
Different font display on mobile phone

### ISSUE THREAD

**Issue by Sdbns** [WPRN/website#28]
I noticed that the homepage font changes on mobile phones between two browsers: qwant and google. It's on the google browser that the font differs. Maybe a bug? 

![AFFICHAGE QWANT](https://user-images.githubusercontent.com/64425631/82184539-1b88b480-98e8-11ea-88fd-98323b1a63f7.jpg)
![AFFICHAGE GOOGLE](https://user-images.githubusercontent.com/64425631/82184542-1cb9e180-98e8-11ea-854e-5673fd75f140.jpg)

**Comment by Billybobbonnet** [comment]
I was aware of it but considering we would switch soon to another page landing I didn't fix it. I assumed it would only be visible like this for a split second, until the actual font is downloaded. It seems that some browser won't download it. (this is "cursive" font family, the fallback).

I'll try an easy fix.

**Comment by Sdbns** [comment]
Ok I wasn't sure you knew about it. And even once the page is fully loaded, the font doesn't change.

**Comment by Billybobbonnet** [comment]
Fixed for now with a more satisfying fallback. We will eventually rework the splash (new tickets welcome)
