### ISSUE TITLE
bug during a search

### ISSUE THREAD

**Issue by Sdbns** [WPRN/website#32]
Seems to be the same bug as last time. When I search for this project name "Quarantine Role in the Control of Corona Virus in the World and Its Impact on the World Economy" this is what appears. 

![BUG SEARCH WPRN 2](https://user-images.githubusercontent.com/64425631/83647613-61669d80-a5b5-11ea-9692-96b2b2890535.png)

**Comment by Billybobbonnet** [comment]
Nice catch :+1: . The highlight feature needs a rework. I'll add a white words filter in the next iteration of the project list page (i.e. remove "and", "the", "in", "of", "its", etc.).

While it's likely not the cause, it would reduce the feedback to relevant words.

**Comment by Billybobbonnet** [comment]
It should be fixed with https://github.com/WPRN/website/issues/38

Let's keep an eye on it and reopen the issue if similar behaviors are occurring.

**Comment by Sdbns** [comment]
Again the same style of bug when searching ... I entered "Digital Trade in a Post-Pandemic Data-Driven Economy" in the search bar. 

<img width="743" alt="BUG SEARCH WPRN 3" src="https://user-images.githubusercontent.com/64425631/86359147-f02c1000-bc70-11ea-954a-dea1317e3d53.png">

**Comment by Billybobbonnet** [comment]
No worries, the updated version is not live on production servers. I should make the next big update this weekend.

**Comment by Sdbns** [comment]
Well noted! Do you want me to list similar bugs anyway? I just saw another one. 
Or should I wait for the update and try again next week?

**Comment by Billybobbonnet** [comment]
No need, the new highlight and truncate function is a complete rework of the previous one and most, if not all, of the bugs should be gone. I'll try to push a test version on tomorrow.

**Comment by Sdbns** [comment]
Thanks! 👍
