### ISSUE TITLE
"register your project" menu tab

### ISSUE THREAD

**Issue by Sdbns** [WPRN/website#33]
I think there's a little bug in the menu. When you go through the menu and click on "register your project", you'll see the form but in the menu it's the tab "about WPRN" which remains underlined.

It is also the same when you simply scroll without going through the menu entries. 

 You have to click a second time on "register your project" to have it underlined. It's a small detail but I don't think I've seen it before ... so is it a bug?

**Comment by Billybobbonnet** [comment]
I knew about this one. It appeared during the many splash changes.. Additionally, when you click on "register project" from the project list, it goes to the right place but does not underline.

**Comment by Sdbns** [comment]
Right, and then I noticed that sometimes I could see "register" in the url and sometimes I couldn't. It's not systematic. Could it be related?
