### ISSUE TITLE
Continents in the project list view (and database)

### ISSUE THREAD

**Issue by sluck-IEA** [WPRN/website#4]
If contributors have selected "Worldwide/intercontinental" in their form and then selected only a few countries, the specific continents of the coutries selected should also be registered in the database, displayed in the project list and found in the search. 
For example, if I only select "Worldwide", and then only "France" (or several other European countries), the project list should also display "Europe" in addition to "Worldwide" and the project sould be found if someones searches for projects in Europe

**Comment by Billybobbonnet** [comment]
I have already the way to fix it in mind. We'll do that in one of the upcoming iterations.
