### ISSUE TITLE
New column view of project list

### ISSUE THREAD

**Issue by sluck-IEA** [WPRN/website#5]
In the project list view, add a column "Institution". To make room for it while keeping enough room for the title of the project, the list should no longer show the "Status" and "Country" column

**Comment by Billybobbonnet** [comment]
Status and Country are search filters and it's better to keep them in view if they are used. I could make them appear only if they are set.

I'll look into it. Maybe we can add the Institution while keeping the other fields.

**Comment by Billybobbonnet** [comment]
Another option would be that we can remove the project status (ongoing, completed etc.) in the row data and replace it with the institution. I'll truncate the institution name to 12 characters to avoid breaking the layout. Would that be ok?

**Comment by sluck-IEA** [comment]
yes!
