### ISSUE TITLE
Bad link in e-mail to share project

### ISSUE THREAD

**Issue by sluck-IEA** [WPRN/website#7]
When one wants to share a project by e-mail, with the email icon in the project page ("Share this project by Email"), the link created in the automatic e-mail is wrong because it includes the "best" of "best regards".
Example: 
Hello,Please check this project "gergsrg esgersg " on WPRN (World Pandemic Research Network): https://wprn.org/item/414752Best regards,

There should also be a space and a line between "Hello," and "check"

**Comment by Billybobbonnet** [comment]
Done. I also removed the Pinterest button.
