### ISSUE TITLE
Edition interface for a submitted project: continue button and edition zone

### ISSUE THREAD

**Issue by sluck-IEA** [WPRN/website#8]
When one arrives at the project edition interface (after clicking on the link in the submission confirmation e-mail), the first edition zone is "General info", and the "continue button" is inactive. It becomes active only when one clicks on one of the edition zones ""General info", "Project details", "Location", or "Contact". Could it be active right from the start?

All the edition zones are readily clickable with the pen icon. It is convenient (if one knows one wants to edit just a specific section) but also makes it less clear in which zone you are (General, or project, or location...). Maybe the active zone should be highlighted differently? Or the edition form could just work just like in the submission mode, step by step with only the "previous" and "continue" buttons?

**Comment by sluck-IEA** [comment]
These comments concern the test website

**Comment by Billybobbonnet** [comment]
The continue button part is fixed. For the distinction between active zones, I underlined the step label. I need to come up with another way since the labels are hidden on mobile.

**Comment by Billybobbonnet** [comment]
Ok. I changed the color of the active step icon. It should cover it for both mobile & desktop. Feel free to reopen this if it is not satisfactory (after update).
